port = 49000
system_tray = disabled
upnp = disabled
origin_web_ui_allowed = pc
controller = enabled
gamepad = auto
motion_as_ds4 = enabled
touchpad_as_ds4 = enabled
ds4_back_as_touchpad_click = enabled
dd_configuration_option = disabled
dd_resolution_option = disabled
dd_refresh_rate_option = disabled
dd_hdr_option = disabled
dd_config_revert_delay = 3000
dd_config_revert_on_disconnect = disabled
file_apps = apps.json
credentials_file = ../../moonlight/server/sunshine-shared/sunshine_state.json
file_state = ../../moonlight/server/sunshine-shared/sunshine_state.json
log_path = sunshine.log
pkey = ../../moonlight/server/sunshine-shared/credentials/cakey.pem
cert = ../../moonlight/server/sunshine-shared/credentials/cacert.pem
capture = ddx
audio_sink = Speakers (Steam Streaming Speakers)
virtual_sink = Speakers (Steam Streaming Speakers)
encoder = nvenc
nvenc_realtime_hags = disabled
nvenc_latency_over_power = enabled
